version: '3.5'

services:
  api:
    build:
      context: ./entrance
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    environment:
      PORT: 3000
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: dbname

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pginit/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./pginit/tables/users.sql:/docker-entrypoint-initdb.d/02_users.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redisdata:/data


volumes:
  pgdata:
  redisdata:
networks:
  app-network:
    driver: bridge
    name: my_shared_network
